package:
  name: chart-testing
  version: "3.12.0"
  epoch: 13
  description: Tool for testing Helm charts, used for linting and testing pull requests.
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/helm/chart-testing
      tag: v${{package.version}}
      expected-commit: d6991035017d7ac0e3dec3d1b5ad2e5f18674b32

  - uses: go/build
    with:
      modroot: .
      packages: ./ct
      output: ct
      ldflags: "-X github.com/helm/chart-testing/v3/ct/cmd.Version=${{package.version}} -X github.com/helm/chart-testing/v3/ct/cmd.BuildDate=$(date -u +%Y-%m-%dT%H:%M:%SZ) -X github.com/helm/chart-testing/v3/ct/cmd.GitCommit=$(git rev-parse --short HEAD)"

update:
  enabled: true
  github:
    identifier: helm/chart-testing
    strip-prefix: v
test:
  pipeline:
    - name: "Version test"
      runs: |
        ct version