package:
  name: figlet
  version: 2.2.5
  epoch: 15
  description: Program that creates large characters out of ordinary screen characters.
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle

pipeline:
  # We can't use go/install because this requires a specific go version
  - uses: git-checkout
    with:
      repository: https://github.com/cmatsuoka/figlet
      branch: master

  - name: Configure and build
    runs: |
      make clean
      DEFAULTFONTDIR=/usr/share/figlet/fonts make all

  - name: Install Figlet and Fonts
    runs: |
      make DESTDIR="${{targets.destdir}}" BINDIR=/usr/bin MANDIR=/usr/share/man DEFAULTFONTDIR=/usr/share/figlet/fonts install

  - name: "Debug: Check paths"
    runs: |
      echo "Available binaries in /usr/bin:"
      ls -l /usr/bin/
      echo "Available binaries in /bin:"
      ls -l /bin/

update:
  enabled: false
  exclude-reason: Setting the update to false since the package no longer receives updates.

test:
  environment:
    contents:
      packages:
        - bash
        - file
  pipeline:
    - name: "Basic functionality"
      runs: |
        if ! command -v figlet >/dev/null; then
        echo "Figlet binary not found!"
        exit 1
        fi
        # echo "Hello" | figlet
    - name: "Figlet custom font support"
      runs: |
        figlet -d /usr/share/figlet/fonts -f slant "Test" >> test.txt
        cat test.txt
    - name: "Check if Figlet is statically linked"
      runs: |
        if ldd $(command -v figlet) >/dev/null 2>&1; then
        echo "Figlet is dynamically linked!"
        exit 1
        fi
    - name: "Test monitoring server startup"
      runs: |
        file $(command -v figlet) | grep "statically linked"
