package:
  name: figlet
  version: 2.2.5
  epoch: 0
  description: Program that creates large characters out of ordinary screen characters.
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - build-base
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/cmatsuoka/figlet
      branch: master

  - name: Configure and build
    runs: |
      make clean
      make DESTDIR="${{targets.destdir}}" BINDIR=/usr/bin MANDIR=/usr/share/man DEFAULTFONTDIR=/usr/share/figlet/fonts install

update:
  enabled: false
  exclude-reason: Setting the update to false since the package no longer receives updates.

test:
  environment:
    contents:
      packages:
        - bash
        - git
  pipeline:
    - name: "Basic functionality"
      runs: |
        figlet -v | grep -q "${{package.version}}"
    - name: Clone Test Repository
      runs: |
        git clone https://github.com/cmatsuoka/figlet.git
    - name: Configure tests to run with installed figlet, not local binary
      runs: |
        sed -i 's|CMD="./figlet"|CMD="figlet"|' figlet/run-tests.sh
        sed -i 's|FIGLET=$DIR/figlet|FIGLET="figlet"|' figlet/showfigfonts
        sed -i 's|$cmd -f  tests/flowerpower -R|$CMD -f tests/flowerpower -R "figlet"|' figlet/run-tests.sh
    - name: Run Figlet Tests
      runs: |
        cd figlet
        ./run-tests.sh
