package:
  name: gluster
  version: "11.2"
  epoch: 0
  description: Tools for the Bluetooth protocol stack
  copyright:
    - license: LGPL-3.0 AND GPL-2.0

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - bison
      - busybox
      - libtool
      - ca-certificates-bundle
      - tcmalloc
      - tcmalloc-minimal
      - gperftools-dev
      - intltool
      - pkgconf-dev
      - rpcgen
      - flex
      - openssl
      - openssl-dev
      - libuuid
      - util-linux-dev
      - acl-dev
      - zlib-dev
      - python3
      - libxml2-dev
      - libtirpc-dev
      - nfs-utils-dev
      - liburing-dev


pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/gluster/glusterfs
      tag: v${{package.version}}
      expected-commit: 15d3c0f8435814fdb7242a8a82fa5db140013d0a
  - runs: |
      ./autogen.sh
  - uses: autoconf/configure
    with:
      opts: |
        --disable-uuidd \
        --disable-libuuid

  - uses: autoconf/make

  - runs: autoconf/make-install

  - uses: strip

update:
  enabled: false

test:
  environment:
    contents:
      packages:
        - python3
        - dbus
  pipeline:
    # Test version commands
    - name: Test version commands
      runs: |
        bluemoon --version
        bluetoothctl --version
        btattach --version
        ciptool --version
        hciconfig --version
        hcidump --version
        hcitool --version
        hex2hcd --version
        mesh-cfgclient --version
        mesh-cfgtest --version
        mpris-proxy --version
        rfcomm --version
    # Test help commands
    - name: Test help commands
      runs: |
        bluemoon --help
        btattach --help
        ciptool --help
        hciconfig --help
        hcidump --help
        hcitool --help
        hex2hcd --help
        mesh-cfgtest --help
        mpris-proxy --help
        rfcomm --help
        sdptool --help
    # Test bluetoothctl functionality
    - name: Test bluetoothctl basic commands
      runs: |
        # Test non-interactive commands
        # exit 0 since bluetoothctl doesn't have access to
        #
        bluetoothctl --help && exit 0;
    # Test hciconfig functionality
    - name: Test hciconfig basic commands
      runs: |
        # List HCI devices (may be empty in test environment)
        hciconfig --help
    # Test hcitool functionality
    - name: Test hcitool basic commands
      runs: |
        # Test device info commands
        hcitool dev || [ $? -eq 1 ]
        hcitool inq || [ $? -eq 1 ]
    # Test gatttool functionality
    - name: Test gatttool basic commands
      runs: |
        # Test gatttool parameters
        gatttool --help-all
        gatttool --help-gatt
        gatttool --help-params
        gatttool --help-char-read-write
    # Test shared libraries and dependencies
    - uses: test/tw/ldd-check
