package:
  name: kubescape-storage
  version: "0.0.185"
  epoch: 0
  description: An Aggregated APIServer for the Kubescape internal storage services.
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubescape/storage
      expected-commit: 342eb9da9bbc8e54e780ca3d2b5faae35d7deedf
      tag: v${{package.version}}

  - uses: go/build
    with:
      packages: .
      output: storage

update:
  enabled: true
  ignore-regex-patterns:
    - 'rc\d+$'
  github:
    identifier: kubescape/storage
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - kubectl
  pipeline:
    - uses: test/kwok/cluster
    - runs: |
        storage --help
    - name: "Setup config"
      runs: |
        # wait until you have a serviceaccount default
        while ! kubectl get serviceaccount default -n kube-system; do
          echo "Waiting for serviceaccount default in kube-system namespace..."
          sleep 1
        done
        mkdir -p /var/run/secrets/kubernetes.io/serviceaccount
        kubectl create token default > /var/run/secrets/kubernetes.io/serviceaccount/token

        mkdir -p /etc/config
        cat > /etc/config/config <<EOF
        {
          "someConfig": "value"
        }
        EOF

        # Cluster data file
        cat > /etc/config/clusterData.json <<EOF
        {
          "clusterName": "test-cluster",
          "region": "us-test1"
        }
        EOF
    - name: "Functional test"
      runs: |
        export KUBERNETES_SERVICE_HOST=127.0.0.1
        export KUBERNETES_SERVICE_PORT=443
        storage serve 2>&1 | tee /logs.txt
        # Negative functional tests since kubescape needs to be deployed at pod service
        grep -q "APIServer started" /logs.txt
