package:
  name: longhorn-instance-manager
  version: "1_20221003"
  epoch: 0
  description: Longhorn Instance Manager manages engine and replica instances on the node.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      # - glibc-dev
      # - libqcow-dev
      # - zlib-dev
      # - zlib-static

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/longhorn/longhorn-instance-manager
      tag: v${{package.version}}
      expected-commit: 65135bc070cdbe4b113c9d36b19671edf6194c7b
  - uses: go/bump
    with:
      deps: |
        github.com/longhorn/backupstore@v0.0.0-20221114044558-19f4902cd4fd
        github.com/longhorn/longhorn-engine@v1.3.1-0.20221115055520-8179e277e475
      tidy: false
  - uses: go/build
    with:
      packages: .
      output: longhorn-instance-manager
      tidy: true
      vendor: true
      ldflags: |
        -X main.Version=${{package.version}}
        -X main.GitCommit="dea869bf5915a8eda646e87a50e13eb1cdca1040"
        -X main.BuildDate=$(date ${SOURCE_DATE_EPOCH:+ -d@${SOURCE_DATE_EPOCH}} "+%Y-%m-%dT%H:%M:%SZ")
        -linkmode external -extldflags "-static"


subpackages:
  - name: ${{package.name}}-compat
    description: Compat package for ${{package.name}}
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/usr/local/bin
          ln -s /usr/bin/longhorn-instance-manager "${{targets.contextdir}}"/usr/local/bin/longhorn-instance-manager

update:
  enabled: true
  ignore-regex-patterns:
    - '2_*'
  github:
    identifier: longhorn/longhorn-instance-manager
    strip-prefix: v

test:
  pipeline:
    - name: Test Version and help commands
      runs: |
        longhorn-instance-manager --version