package:
  name: nats-top
  version: "0.6.3"
  epoch: 0
  description: A top-like tool for monitoring NATS servers.
  copyright:
    - license: MIT

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/nats-io/nats-top
      tag: v${{package.version}}
      expected-commit: 812d35cc991232d7606816a15b2ea0b12fb129e7

  - uses: go/build
    with:
      packages: .
      output: nats-top
      ldflags: -X main.version=${{package.version}} -X main.commit=$(git rev-parse HEAD) -X main.date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

subpackages:
  - name: ${{package.name}}-compat
    description: Compat package for ${{package.name}}
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/usr/local/bin
          ln -s /usr/bin/nats-top "${{targets.contextdir}}"/usr/local/bin/nats-top

update:
  enabled: true
  github:
    identifier: nats-io/nats-top
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - nats-server
        - nats
        - util-linux-misc
        - mkcert
        - openssl
  pipeline:
    - name: "Version test"
      runs: |
        nats-top --version 2>&1 | grep ${{package.version}}
    - name: Test nats-top with minimal nats server and 2 clients
      runs: |
        nats-server -p 4222 -m 8222 & sleep 2 &
        nats sub client1 > /dev/null & sleep 2 & nats sub client2 > /dev/null & sleep 2
        nats-top -s localhost -b -u -o nats-output-${{package.version}}.txt
        cat nats-output-${{package.version}}.txt
    - name: test connection limit (-n) and sorting options (-sort)
      runs: |
        nats-top -n 1 -sort uptime -o nats-output-${{package.version}}.txt
        grep "Connections Polled: 1" nats-output-${{package.version}}.txt >/dev/null 2>&1
    - name: test output with delimiter (-l)
      runs: |
        nats-top -o nats-output-${{package.version}}.csv -l ","
        if [ ! -s "nats-output-${{package.version}}.csv" ]; then
          echo "Error: CSV File is empty!"
          exit 1
        fi
        head -n 5 "nats-output-${{package.version}}.csv"
    - name: test setting refresh delay (-d) and refresh count (-r)
      runs: |
        export TERM=xterm && timeout 3 script -q -c "nats-top -d 1 -r 3" /dev/null
    - name: Test Nats-top in TLS mode
      runs: |
        mkdir -p /tmp/certs
        cd /tmp/certs
        # Using mkcert to generate certs
        mkcert -install
        mkcert -cert-file server-cert.pem -key-file server-key.pem localhost 127.0.0.1
        mkcert -client -cert-file client-cert.pem -key-file client-key.pem localhost 127.0.0.1
        cp "$(mkcert -CAROOT)/rootCA.pem" ca-cert.pem
        cd ../..
        # Killing previous nats-server process
        pkill nats-server & sleep 2
        # Certs validation before injecting them into NATS
        openssl verify -CAfile ./tmp/certs/ca-cert.pem ./tmp/certs/server-cert.pem
        openssl verify -CAfile ./tmp/certs/ca-cert.pem ./tmp/certs/client-cert.pem
        # Setting up NATS server
        nats-server -p 4223 -m 8223 --tls --tlscert ./tmp/certs/server-cert.pem --tlskey ./tmp/certs/server-key.pem --tlscacert ./tmp/certs/ca-cert.pem & sleep 2
        # Creating a NATS client and publishing sample message
        nats sub -s "localhost:4223" --tlscert ./tmp/certs/client-cert.pem --tlskey ./tmp/certs/client-key.pem --tlsca ./tmp/certs/ca-cert.pem "test.subject" > /dev/null & sleep 1
        # Test NATS top in TLS mode
        nats-top -s localhost -m 8223 -cert ./tmp/certs/client-cert.pem -key ./tmp/certs/client-key.pem -cacert ./tmp/certs/ca-cert.pem -o nats-output-${{package.version}}.txt
        cat nats-output-${{package.version}}.txt
