package:
  name: nats-box
  version: 0.16.0
  epoch: 30
  description: NATS utilities toolbox.
  dependencies:
    runtime:
      - bash
      - ca-certificates
      - curl
      - figlet
      - jq
      - nats
      - nats-top
      - nsc
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/nats-io/nats-box
      tag: v${{package.version}}
      expected-commit: b73821692fc596b210816de93c5011047298646b

  - runs: |
      mkdir -p ${{targets.destdir}}/etc/profile.d
      sed -i 's/^.*MARKER-REPLACE-LINE-IN-CI.*/echo "nats-box v${{package.version}}" >\&2/' profile.sh
      mv profile.sh ${{targets.destdir}}/etc/profile.d
      mv entrypoint.sh ${{targets.destdir}}/entrypoint.sh
      chmod 777 ${{targets.destdir}}/entrypoint.sh

update:
  enabled: true
  github:
    identifier: nats-io/nats-box
    strip-prefix: v

test:
  pipeline:
    - name: "Verify entrypoint.sh and profile.sh files"
      runs: |
        test -s "../../etc/profile.d/profile.sh"
        test -s "../../entrypoint.sh"
