package:
  name: tofu-controller
  version: "0.15.1"
  epoch: 0
  description: Tofu Controller (previously known as Weave TF-Controller) is a controller for Flux to reconcile OpenTofu and Terraform resources in the GitOps way.
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/flux-iac/tofu-controller
      tag: v${{package.version}}
      expected-commit: a53488094851773978301511922c2ced1397cdf9

  - uses: go/build
    with:
      extra-args: -gcflags="-N -l"
      packages: ./cmd/manager
      output: tofu-controller
      ldflags: |
        -X main.BuildVersion=${{package.version}}
        -X main.BuildSHA=$(git rev-parse HEAD)

subpackages:
  - name: ${{package.name}}-compat
    description: Compat package for ${{package.name}}
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/usr/local/bin
          ln -sf /usr/bin/tofu-controller "${{targets.contextdir}}"/usr/local/bin/tofu-controller

update:
  enabled: true
  ignore-regex-patterns:
    - '-rc'
  github:
    identifier: flux-iac/tofu-controller
    use-tag: true
    strip-prefix: v

test:
  pipeline:
    - uses: test/kwok/cluster
    - name: "Install required CRD for tofu controller to pick up"
      runs: |
        cat <<EOF | kubectl apply -f -
        apiVersion: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        metadata:
          name: terraforms.infra.contrib.fluxcd.io
        spec:
          group: infra.contrib.fluxcd.io
          names:
            kind: Terraform
            listKind: TerraformList
            plural: terraforms
            singular: terraform
          scope: Namespaced
          versions:
            - name: v1alpha2
              served: true
              storage: true
              schema:
                openAPIV3Schema:
                  type: object
        EOF
    - name: "Start tofu-controller"
      runs: |
        tofu-controller > /tmp/tofu-controller.log 2>&1 &
        sleep 3
        ps aux | grep -q tofu-controller
    - name: "Validations"
      runs: |
        grep -q "Starting manager" /tmp/tofu-controller.log
        grep -q "Starting server" /tmp/tofu-controller.log
        grep -q "Starting EventSource" /tmp/tofu-controller.log
        grep -q "Starting Controller" /tmp/tofu-controller.log
